---
kind: ConfigMap
apiVersion: v1
metadata:
  name: '{{ .Values.SERVICE_NAME }}.monitoring-config'
  labels:
    app.kubernetes.io/name: "{{ .Values.SERVICE_NAME }}"
    deployment.qubership.org/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
data:
  url.health: http://%(ip)s:8080/health
  url.metrics: http://%(ip)s:8080/metrics
  prometheus.url.metrics: http://%(ip)s:8080/prometheus
  group.metrics.counter.status.all: ^counter.status..+
  group.metrics.gauge.response.all: ^gauge.response..+