---

  # This GitHub Actions workflow is designed to be triggered when a release is marked as a full release.
  # The workflow performs the following tasks:
  # 1. Checks if the tag already exists.
  # 2. Updates the version in the pom.xml file.
  # 3. Commits the changes to the repository.
  # 4. Builds the project using Maven.
  # 5. Runs tests.
  # 6. Tags the commit with the release version.
  # 7. Publishes the artifact to the Maven repository.
  # 8. Builds and publishes a Docker image.
  # 9. Creates a GitHub release.
  
  # To make it work for your project, you need to adjust the pom.xml and add configuration file for GitHub release.
  # Please find detailed instructions:
  # https://github.com/Netcracker/qubership-workflow-hub?tab=readme-ov-file#maven-project-release-workflow
  
  name: Dbaas Release
  
  on:
    workflow_dispatch:
      inputs:
        version-type:
          description: 'Version type to release. Can be one of [major, minor, patch]'
          required: true
          default: 'patch'
          type: string
        java_version:
          required: false
          type: string
          default: "21"
          description: 'Java version (e.g., 21)'
        build-docker:
          required: false
          type: boolean
          default: true
          description: 'Release docker image if there is Docker file'
        dry-run:
          required: false
          type: boolean
          default: false
          description: 'Dry run'
        profile:
          description: 'Maven profile to use'
          type: choice
          options:
            - 'github'
            - 'central'
          required: true
          default: 'central'
  permissions:
    contents: write
    packages: write
  
  jobs:
    dry-run-build:
      runs-on: ubuntu-latest
      steps:
        - name: "Build and Publish"
          uses: netcracker/qubership-workflow-hub/actions/maven-release@main
          with:
            version-type: ${{ github.event.inputs.version-type }}
            module: ${{ github.event.repository.name }}
            maven-args: ${{ inputs.mvn-args }}
            profile: ${{ inputs.profile }}
            token: ${{ secrets.GITHUB_TOKEN }}
            gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
            gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
            dry-run: 'true'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    publish:
      needs: dry-run-build
      if: ${{ needs.dry-run-build.result == 'success' }}
      outputs:
        release-version: ${{ steps.build-and-publish.outputs.release-version }}
      runs-on: ubuntu-latest
      steps:
        - name: "Build and Publish"
          id: build-and-publish
          uses: netcracker/qubership-workflow-hub/actions/maven-release@main
          with:
            version-type: ${{ github.event.inputs.version-type }}
            module: ${{ github.event.repository.name }}
            maven-args: ${{ inputs.mvn-args }}
            token: ${{ secrets.GITHUB_TOKEN }}
            server-id: ${{ inputs.profile }}
            profile: ${{ inputs.profile }}
            gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
            gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
            dry-run: 'false'